
spring.datasource.url=jdbc:postgresql://localhost:5432/pickem_dev?sslmode=disable
spring.datasource.username=gbaduqui
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true   