
spring.datasource.url=jdbc:postgresql://localhost:5432/pickem_dev?sslmode=disable&currentSchema=pickem
spring.datasource.username=gbaduqui
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=pickem
spring.jpa.show-sql=true